### ISSUE TITLE
find suitable web theme

### ISSUE THREAD

**Issue by paragasu** [phisoft/wecomplain-web#1]

**Comment by paragasu** [comment]
https://technext.github.io/app/index.html

**Comment by russel0907** [comment]
## Upload web template to repository

![Screenshot 2022-08-05 at 12-00-33 App — Free Website Template Free HTML5 Template by FreeHTML5 co](https://user-images.githubusercontent.com/94702093/182998923-423b19fe-0526-4e7a-a92b-5575e6207267.png)
